# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: postgresql
  database: matchup_development

test: &TEST
  adapter: postgresql
  database: matchup_test

cucumber:
  <<: *test
